# Generated by Django 3.2.15 on 2022-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketCap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latest', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('_1h_perc', models.CharField(max_length=200)),
                ('_24h_perc', models.CharField(max_length=200)),
                ('_7d_perc', models.CharField(max_length=200)),
                ('market_cap', models.CharField(max_length=200)),
                ('volume_24h', models.CharField(max_length=200)),
                ('circulating_supply', models.CharField(max_length=200)),
            ],
        ),
    ]
